In [1]:
import numpy as np

In [2]:
a = np.array([3, 4, 5])

In [3]:
a[0]

3

In [4]:
b = np.array([[2,3,4], [3,4,5]])

In [5]:
b.ndim

2

In [6]:
a.ndim

1

In [7]:
a.itemsize

8

In [8]:
b.itemsize

8

In [10]:
a.dtype

dtype('int64')

In [11]:
a.dtype = float

In [12]:
a.dtype

dtype('float64')

In [13]:
a.itemsize

8

In [14]:
a

array([1.5e-323, 2.0e-323, 2.5e-323])

In [15]:
a.size

3

In [16]:
b.size

6

In [17]:
b.shape

(2, 3)

In [18]:
a.shape

(3,)

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [31]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
b.reshape(3,2)

array([[2, 3],
       [4, 3],
       [4, 5]])

In [34]:
b.reshape(6, 1)

array([[2],
       [3],
       [4],
       [3],
       [4],
       [5]])

In [39]:
b.ravel()

array([2, 3, 4, 3, 4, 5])

In [40]:
b

array([[2, 3, 4],
       [3, 4, 5]])

In [41]:
b.min()

2

In [42]:
b.max()

5

In [44]:
np.sqrt(b)

array([[1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798]])

In [45]:
np.std(b)

0.9574271077563381

In [49]:
a = np.array([[2,3] , [4,5]])

In [50]:
b = np.array([[1,5], [2, 4]])

In [51]:
a+b

array([[3, 8],
       [6, 9]])

In [52]:
a.dot(b)

array([[ 8, 22],
       [14, 40]])

In [53]:
a*b

array([[ 2, 15],
       [ 8, 20]])

# list vs np array

In [54]:
size = 1000

In [55]:
l1 = range(size)

In [56]:
l2 = range(size)

In [59]:
a1 = np.arange(size)

In [60]:
a2 = np.arange(size)

In [62]:
import time

In [63]:
start = time.time()

In [64]:
result = [(x+y) for x,y in zip(l1, l2)]

In [66]:
print(time.time() - start)

87.44592213630676


In [68]:
start = time.time()

In [69]:
result = a1 + a2

In [70]:
print(time.time()-start)

17.761931896209717
